### ISSUE TITLE
Expose parser

### ISSUE THREAD

**Issue by dy** [observablehq/htl#3]
HTL is nice sugared alternative to [htm](https://ghub.io/htm) and [hyperx](https://ghub.io/hyperx).
Would be nice to be able to use its parser separately, for eg. VDOM purposes.

**Comment by mbostock** [comment]
What do you have in mind? HTL doesn’t construct an intermediate representation of the DOM that would be suitable for passing to a VDOM implementation (such as HyperScript or React.createElement). Instead, HTL concatenates markup which is then parsed by the browser using a template element.

We could expose the generated markup, but I don’t see how that would be especially useful outside of this library since it will contain the attribute and data placeholders (e.g., an attribute named “::1” or a comment “&lt;!--::2-->”).

**Comment by dy** [comment]
I see. Yes, there doesn’t seem to be a simple way to convert html string
with placeholders to hyperscript.
Only if using htm for that purpose)
I guess that can be closed then.

**Comment by mbostock** [comment]
Copy that. Thanks for the suggestion regardless!
