### ISSUE TITLE
Whitespace surrounding elements is not trimmed

### ISSUE THREAD

**Issue by j-f1** [observablehq/htl#5]
The current `html` template literal strips surrounding whitespace from the provided HTML:

<img width="105" alt="Screen Shot 2019-12-11 at 16 16 49" src="https://user-images.githubusercontent.com/25517624/70661142-a5de3580-1c31-11ea-9bb5-1197aafc4bd5.png">

However, attempting to do the same with `htl`‘s `html` tag results in a `DocumentFragment` being created. Would it be possible to strip whitespace from around the outermost tag, especially if it’s a block element where the whitespace won’t have any visible effect?

https://observablehq.com/d/45bf892f168caab1

**Comment by hastebrot** [comment]
This also causes a problem with `svg`. Adding a new line at the end of the template string will wrap `<svg>` into a `<g>` and renders nothing.

~~~js
svg`<svg width=60 height=60>
  ${svg`<circle cx=30 cy=30 r=30></circle>`}
</svg>
`
~~~

**Comment by mbostock** [comment]
This is the intended behavior. Hypertext literal is not JSX, and does not do any implicit whitespace trimming. It preserves the input exactly, so if you don’t want the surrounding whitespace, you should remove it from the input.

**Comment by mbostock** [comment]
To elaborate slightly, one reason we don’t trim whitespace is that it *can* have a visible effect. For example, consider this expression:

```js
html`<div>hello${html` <span>to the</span> `}world</div>`
```

If we trimmed whitespace, then the resulting display would be `helloto theworld`. But if we don’t trim whitespace, then the resulting display is `hello to the world`. The hypertext literal can’t determine whether the whitespace will be visible or not because it depends on context, and we want the behavior of hypertext literal to be predictable and accurately reflect the input. Hence, we don’t trim whitespace.
